openapi: 3.0.1
info:
  title: Product Microservice Demo
  description: product CRUD API.
  version: 1.0.0
servers:
  - url: http://localhost:8080/product
paths:
  /product:
    get:
      summary: Get All Product
      operationId: getCategories
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Add a product
      operationId: addProduct
      requestBody:
        description: Product to be added in shop
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        200:
          description: Product Added
          content:
            application/json:
              schema:
                type: string
      x-codegen-request-body-name: product
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        categories-id:
          type: integer
          format: int64
        name:
          type: string
          example: dellA1234
        price:
          type: number

