server:
  port: 8085
spring:
  application:
    name: category-service
# datasourse
  jpa:
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://database:5432/thuongmaidientu
    username: "postgres"
    password: "123456""
    driver-class-name: org.postgresql.Driver