openapi: 3.0.1
info:
  title: Categories Microservice Demo
  description: Categories CRUD API.
  version: 1.0.0
servers:
  - url: http://localhost:8080/categories
paths:
  /categories:
    get:
      summary: Get All Product
      operationId: getCategories
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Categories'
    post:
      summary: Add a Categories
      operationId: addCategories
      requestBody:
        description: Categories to be added in shop
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Categories'
        required: true
      responses:
        200:
          description: Categories Added
          content:
            application/json:
              schema:
                type: string
      x-codegen-request-body-name: categories
components:
  schemas:
    Categories:
      type: object
      properties:
        id:
          type: integer
          format: int64
        categories-name:
          type: string
          example: LapTop
        product-name:
          type: string
          example: dell
